session_name: Memos-API
windows:
  - window_name: Memos-API
    layout: main-vertical
    options:
      main-pane-width: 20%
    panes:
      - shell_command:
          - cd ~/Documents/Notes/Projects/memos-api
          # - nvim Notes.md ToDo.md
          - open-project
      - shell_command:
          - tmux resizep -y 85%
          - filelist-open "startup_files.txt" memos-api
        focus: true
      - clear
